<?php
/**
 * Extract dead code from functions.php and wrap each top-level function
 * in a function_exists() guard. Output to functions_legacy.php.
 *
 * Approach: tokenize the ENTIRE file (not a substring) so PHP's tokenizer
 * handles all strings/comments/heredocs correctly. Track brace depth at
 * the token level. Functions at depth=0 are top-level and get wrapped.
 *
 * Usage: php tools/wrap_legacy_functions.php
 */

$source = __DIR__ . '/../includes/functions.php';
$output = __DIR__ . '/../includes/functions_legacy.php';

// Read entire file as lines
$all_lines = file($source, FILE_IGNORE_NEW_LINES);
$total = count($all_lines);

// Find the return; statement
$return_line_idx = null;
for ($i = 0; $i < $total; $i++) {
    if (trim($all_lines[$i]) === 'return;') {
        $return_line_idx = $i;
        break;
    }
}

if ($return_line_idx === null) {
    die("ERROR: Could not find 'return;' line in functions.php\n");
}

echo "Found 'return;' at line " . ($return_line_idx + 1) . "\n";

// Extract dead code (everything after return;)
$dead_lines = array_slice($all_lines, $return_line_idx + 1);
$dead_code = implode("\n", $dead_lines);

// Tokenize WITH <?php prefix so the tokenizer works correctly
$full_code = "<?php\n" . $dead_code;
$tokens = token_get_all($full_code);

// Build output using token stream
// Strategy: find each top-level function, note its name.
// Track brace depth. When depth returns to function start depth, close guard.

$functions_found = [];
$result_tokens = []; // array of strings to join

$depth = 0;
$func_stack = []; // stack of ['name'=>..., 'start_depth'=>...] for nested tracking

$i = 0;
$len = count($tokens);

// Skip the <?php token we added
if ($len > 0 && is_array($tokens[0]) && $tokens[0][0] === T_OPEN_TAG) {
    $i = 1;
}

while ($i < $len) {
    $token = $tokens[$i];
    $is_arr = is_array($token);
    $token_str = $is_arr ? $token[1] : $token;
    $token_type = $is_arr ? $token[0] : null;

    // Detect function keyword at the current brace depth
    if ($token_type === T_FUNCTION) {
        // Look ahead for function name (skip whitespace and possible & for references)
        $j = $i + 1;
        $found_name = null;
        while ($j < $len) {
            $nt = $tokens[$j];
            if (is_array($nt) && ($nt[0] === T_WHITESPACE || $nt[0] === T_COMMENT || $nt[0] === T_DOC_COMMENT)) {
                $j++;
                continue;
            }
            // Skip & for reference returns
            if (!is_array($nt) && $nt === '&') {
                $j++;
                continue;
            }
            if (is_array($nt) && $nt[0] === T_STRING) {
                $found_name = $nt[1];
            }
            break;
        }

        if ($found_name !== null && $depth === 0) {
            // Top-level function — insert guard BEFORE
            $result_tokens[] = "if (!function_exists('" . $found_name . "')) {\n";
            $func_stack[] = ['name' => $found_name, 'start_depth' => $depth];
            $functions_found[] = $found_name;
        }
    }

    // Output token
    $result_tokens[] = $token_str;

    // Track braces
    if (!$is_arr) {
        if ($token === '{') {
            $depth++;
        } elseif ($token === '}') {
            $depth--;
            // Check if we closed a tracked function
            if (!empty($func_stack)) {
                $top = end($func_stack);
                if ($depth === $top['start_depth']) {
                    $result_tokens[] = "\n} // end guard: " . $top['name'] . "\n";
                    array_pop($func_stack);
                }
            }
        }
    }

    // Handle T_CURLY_OPEN and T_DOLLAR_OPEN_CURLY_BRACES (inside strings)
    // These also increase depth and get closed by regular '}'
    if ($is_arr && ($token_type === T_CURLY_OPEN || $token_type === T_DOLLAR_OPEN_CURLY_BRACES)) {
        $depth++;
    }

    $i++;
}

// Build the output file
$header = '<?php
/**
 * Legacy function definitions — being migrated to modules.
 * Each function is wrapped in a function_exists() guard so module
 * definitions take precedence when loaded first.
 *
 * Generated by tools/wrap_legacy_functions.php on ' . date('Y-m-d H:i:s') . '
 * Source: includes/functions.php lines ' . ($return_line_idx + 2) . '-' . $total . '
 * Functions wrapped: ' . count($functions_found) . '
 */

';

$result_str = implode('', $result_tokens);
$final = $header . $result_str;

file_put_contents($output, $final);

echo "Generated: $output\n";
echo "Functions wrapped: " . count($functions_found) . "\n";
echo "Final depth: $depth (should be 0)\n";

// Show first 20 and last 10
echo "First 20 functions:\n";
for ($k = 0; $k < min(20, count($functions_found)); $k++) {
    echo "  - " . $functions_found[$k] . "\n";
}
if (count($functions_found) > 30) {
    echo "  ...\n";
    echo "Last 10 functions:\n";
    for ($k = max(0, count($functions_found) - 10); $k < count($functions_found); $k++) {
        echo "  - " . $functions_found[$k] . "\n";
    }
}

echo "\nDone.\n";
